name: CI/CD Pipeline for Airline Management System

on:
  push:
    paths:
      - P4_Group2_Airline_Management_System/**  # Monitor all files in the directory
      - .github/workflows/**                    # (Optional) Monitor workflow file changes

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run Tests
      - name: Run SQL Linting and Tests
        run: |
          echo "Running tests for P4_Group2_Airline_Management_System..."
          # Example SQL linting test using sqlfluff
          sqlfluff lint P4_Group2_Airline_Management_System --dialect mysql
          echo "All tests passed!"

      # Step 3: Deploy Changes (If Tests Pass)
      - name: Deploy Changes
        if: ${{ success() }}  # Only runs if the tests succeed
        run: |
          echo "Deploying updated files in P4_Group2_Airline_Management_System..."
          # Example: Add deployment commands (SQL migration or other tasks)
          # mysql -u $DB_USER -p$DB_PASS -h $DB_HOST < P4_Group2_Airline_Management_System/deploy.sql
          echo "Deployment successful!"
