name: CI/CD Pipeline for Airline Management System

on:
  push:
    paths:
      - P4_Group2_Airline_Management_System/**  # Monitor all files in this directory
      - .github/workflows/**                    # (Optional) Monitor workflow file changes

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run Tests
      - name: Run Tests
        run: |
          echo "Running tests for P4_Group2_Airline_Management_System..."
          # Add your testing commands here
          # Example: Run unit tests or validate file changes
          echo "All tests passed!"

      # Step 3: Deploy Changes (If Tests Pass)
      - name: Deploy Changes
        if: ${{ success() }}  # Only runs if the tests succeed
        run: |
          echo "Deploying updates to P4_Group2_Airline_Management_System..."
          # Add your deployment logic here
          # Example: Sync files to a server or update application
          echo "Deployment successful!"
